# Generated by Django 4.2.7 on 2023-11-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_grou',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='cause_of_death',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Accident', 'Accident'), ('Illness', 'Illness'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='needed_organ',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Liver', 'Liver'), ('Kidney', 'Kidney'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organs_to_donat',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Liver', 'Liver'), ('Kidney', 'Kidney'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
