# Generated by Django 4.2.7 on 2023-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0002_user_address_user_age_user_blood_grou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_grou',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
