# Generated by Django 4.2.7 on 2023-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0004_organrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrequest',
            name='donor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='patient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
