# Generated by Django 4.2.7 on 2023-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0005_alter_organrequest_donor_alter_organrequest_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organrequest',
            old_name='donor',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='organ_name',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='patient',
        ),
        migrations.AddField(
            model_name='organrequest',
            name='needed_organ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='patient_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
