# Generated by Django 4.2.7 on 2023-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0006_rename_donor_organrequest_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='donor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
