# Generated by Django 4.2.7 on 2023-11-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ_app', '0007_organrequest_donor_id_alter_organrequest_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organrequest',
            old_name='patient_age',
            new_name='donor_age',
        ),
        migrations.RenameField(
            model_name='organrequest',
            old_name='patient_email',
            new_name='donor_email',
        ),
        migrations.RenameField(
            model_name='organrequest',
            old_name='patient_name',
            new_name='donor_name',
        ),
    ]
